Added Customer States
ynigoreyes/CoffeeShopSimulator pull request #22
Opened 2020-02-26 17:26 UTC by rgoonie

So this is states we talked about for each Person. I will do the states for the Barista and Manager as well. If you have any question or corrections please let me know (i.e. please look at this)

2020-02-26 17:29 UTC, rgoonie commented
@ynigoreyes Is this how you want the states to be made or should i put the enum files somewhere else?

2020-02-26 17:41 UTC, ColeChip approved these changes

2020-02-26 19:51 UTC, ynigoreyes requested changes
So there are two things we can do from here. This is a pretty small PR with no breaking changes. If you want we can merge this in and call it a day, or you can get all the states for all of the different people so that we get all of the states in one PR and we squash and merge so we don’t see all the incremental changes.

Another things, you should def add the getter for the customer state. I think this is the PR that code belongs in.

Thoughts?

2020-02-29 08:14 UTC, rgoonie commented
@ynigoreyes In this, I merged over my other working branch so all additions of the states will be in this pull. I added the gets and sets as you request. The final thing I did was created a `States` package to contain all the enum file inside of the `Models` package.

2020-02-29 17:28 UTC, ynigoreyes approved these changes

2020-02-29 17:28 UTC, merged