Rajeev/validation of events
ynigoreyes/CoffeeShopSimulator pull request #3
Opened 2020-02-13 06:31 UTC by rgoonie

Created the abstract method `validateEvent` in the `CoffeeShopEvent.java` class and filled in the code for the children classes: `CustomerLeavesEvent` and `NewCustomerWalksInEvent`.

Now why did I have two conditional checks: if null and if it is an instance of. We had a discussion about null pointer exceptions and we always want to make sure that we never get one of those. That's the reason for the null check.

As for the `instanceof` conditional, since the abstracted method uses a type `Object` as the parameter, we want to be 100% sure the data we are checking is the data is the type we want to check. 

Inquires: 
1) Did I do the correct thing making it a `public` method.
2) Where do we want to call the validation: in the constructor of the event or after the class is created?

2020-02-14 04:22 UTC, ynigoreyes requested changes

2020-02-14 04:22 UTC, ynigoreyes commented on src/CoffeeShopSimulator/EventBus/Events/CustomerLeavesEvent.java
> +        if(! (data[0] instanceof Customer) ){
We should check to see if all data passed to it is the type that we need. We can break this code by `validateEvent(someActualCustomer, null, null)`

Let's take a look at [this](https://stackoverflow.com/questions/5307172/check-if-all-items-are-the-same-in-a-list)

2020-02-14 04:22 UTC, ynigoreyes commented on src/CoffeeShopSimulator/EventBus/Events/NewCustomerWalksInEvent.java
> +        if(! (data[0] instanceof Customer) ){
Same thing as the first class

2020-02-14 20:19 UTC, rgoonie commented on src/CoffeeShopSimulator/EventBus/Events/CustomerLeavesEvent.java
> +        if(! (data[0] instanceof Customer) ){
Just for confirmation and to make sure I put this right. For this validation and the `NewCustomerWalksInEvent()` we want to make sure all the object we pass are customers correct? Or do we want to make sure that all the objects are the same customer?

2020-02-15 08:20 UTC, ynigoreyes commented on src/CoffeeShopSimulator/EventBus/Events/CustomerLeavesEvent.java
> +        if(! (data[0] instanceof Customer) ){
all data are customers, not necessarily the same one, but they are all of type Customer

2020-02-17 01:27 UTC, ynigoreyes approved these changes

2020-02-17 01:27 UTC, merged